// utils/firebaseAdmin.js - FIXED VERSION

const admin = require('../config/firebase'); // Adjust path to your Firebase initialization

// ✅ Helper function to get current Firebase project info
const getFirebaseProjectInfo = () => {
  try {
    const app = admin.app();
    return {
      projectId: app.options.projectId || process.env.FIREBASE_PROJECT_ID,
      serviceAccountEmail: app.options.credential?.clientEmail || process.env.FIREBASE_CLIENT_EMAIL
    };
  } catch (error) {
    return {
      projectId: process.env.FIREBASE_PROJECT_ID || 'unknown',
      serviceAccountEmail: process.env.FIREBASE_CLIENT_EMAIL || 'unknown'
    };
  }
};

// ✅ Helper function to ensure all data values are strings
const sanitizeData = (data) => {
  const sanitized = {};
  Object.keys(data).forEach(key => {
    // Firebase requires all data values to be strings
    sanitized[key] = String(data[key]);
  });
  return sanitized;
};

const sendNotificationToDevice = async (fcmToken, title, body, data = {}) => {
  try {
    // Log Firebase project info for debugging
    const projectInfo = getFirebaseProjectInfo();
    console.log(`📤 Sending notification using Firebase Project: ${projectInfo.projectId}`);
    console.log(`🔑 FCM Token (first 20 chars): ${fcmToken?.substring(0, 20)}...`);
    
    // ✅ FIXED: Sanitize data to ensure all values are strings
    const sanitizedData = sanitizeData({
      ...data,
      click_action: 'FLUTTER_NOTIFICATION_CLICK'
    });

    const message = {
      notification: {
        title,
        body
      },
      data: sanitizedData,
      token: fcmToken,
      android: {
        priority: 'high',
        notification: {
          sound: 'default',
          channelId: 'order_updates',
          clickAction: 'FLUTTER_NOTIFICATION_CLICK'
        }
      },
      apns: {
        payload: {
          aps: {
            sound: 'default',
            badge: 1,
            category: 'FLUTTER_NOTIFICATION_CLICK'
          }
        }
      },
      webpush: {
        notification: {
          icon: '/icon.png', // Add your icon path
          badge: '/badge.png', // Add your badge path
          requireInteraction: false
        },
        fcmOptions: {
          link: '/' // Default link when notification is clicked
        }
      }
    };

    const response = await admin.messaging().send(message);
    console.log('✅ Successfully sent notification:', response);
    return { success: true, response };
  } catch (error) {
    console.error('❌ Error sending notification:', error);
    console.error('Error details:', {
      code: error.code,
      message: error.message,
      errorInfo: error.errorInfo
    });
    
    // Handle specific error codes
    if (error.code === 'messaging/invalid-registration-token' ||
        error.code === 'messaging/registration-token-not-registered') {
      console.log('⚠️ Invalid or expired FCM token');
      return { success: false, error: 'Invalid FCM token', code: error.code };
    }
    
    // Handle SenderId mismatch error
    if (error.code === 'messaging/mismatched-credential') {
      const projectInfo = getFirebaseProjectInfo();
      console.error('🚨 SENDER ID MISMATCH DETECTED!');
      console.error('═══════════════════════════════════════════════════════');
      console.error('The FCM token was generated by a different Firebase project');
      console.error('than the one configured in your backend.');
      console.error('');
      console.error('Backend Configuration:');
      console.error('  Project ID:', projectInfo.projectId);
      console.error('  Service Account:', projectInfo.serviceAccountEmail);
      console.error('');
      console.error('Expected Client App Projects:');
      console.error('  - saborly-frontend: project "saborly-397b6" (sender: 420029681993)');
      console.error('  - soleyadinoe: project "saborly-397b6" (sender: 420029681993) ✅ Updated');
      console.error('');
      console.error('SOLUTION:');
      console.error('1. Check which Firebase project your client apps are using:');
      console.error('   - Check firebase_options.dart in Flutter apps');
      console.error('   - Check google-services.json for Android');
      console.error('2. Ensure FIREBASE_PROJECT_ID in backend .env matches the client project');
      console.error('   - For saborly-frontend: FIREBASE_PROJECT_ID=saborly-397b6');
      console.error('   - For soleyadinoe: FIREBASE_PROJECT_ID=saborly');
      console.error('3. Ensure the service account credentials belong to the same project');
      console.error('4. Download the correct service account key from Firebase Console');
      console.error('5. If tokens were generated with a different project, users need to:');
      console.error('   - Re-login to get new FCM tokens');
      console.error('   - Or clear app data and reinstall');
      console.error('═══════════════════════════════════════════════════════');
      return { 
        success: false, 
        error: 'SenderId mismatch - Backend and client apps must use the same Firebase project', 
        code: error.code,
        details: {
          backendProjectId: projectInfo.projectId,
          backendServiceAccount: projectInfo.serviceAccountEmail,
          suggestion: 'Check FIREBASE_PROJECT_ID environment variable matches client app configuration',
          expectedProjects: {
            'saborly-frontend': 'saborly-397b6',
            'soleyadinoe': 'saborly-397b6'
          }
        }
      };
    }
    
    return { success: false, error: error.message, code: error.code };
  }
};

// Send notification to multiple devices
const sendNotificationToMultipleDevices = async (fcmTokens, title, body, data = {}) => {
  try {
    if (!Array.isArray(fcmTokens) || fcmTokens.length === 0) {
      return { success: false, message: 'No tokens provided' };
    }

    // ✅ FIXED: Sanitize data to ensure all values are strings
    const sanitizedData = sanitizeData({
      ...data,
      click_action: 'FLUTTER_NOTIFICATION_CLICK'
    });

    const message = {
      notification: {
        title,
        body
      },
      data: sanitizedData,
      tokens: fcmTokens, // Use 'tokens' not 'token' for multiple devices
      android: {
        priority: 'high',
        notification: {
          sound: 'default',
          channelId: 'order_updates',
          clickAction: 'FLUTTER_NOTIFICATION_CLICK'
        }
      },
      apns: {
        payload: {
          aps: {
            sound: 'default',
            badge: 1,
            category: 'FLUTTER_NOTIFICATION_CLICK'
          }
        }
      },
      webpush: {
        notification: {
          icon: '/icon.png',
          badge: '/badge.png',
          requireInteraction: false
        },
        fcmOptions: {
          link: '/'
        }
      }
    };

    const response = await admin.messaging().sendEachForMulticast(message);
    console.log(`✅ Successfully sent ${response.successCount} notifications`);
    console.log(`❌ Failed to send ${response.failureCount} notifications`);
    
    // Log individual failures with detailed error info
    if (response.failureCount > 0) {
      response.responses.forEach((resp, idx) => {
        if (!resp.success) {
          const errorCode = resp.error?.code || resp.error?.errorInfo?.code;
          const errorMessage = resp.error?.message || resp.error?.errorInfo?.message || 'Unknown error';
          console.error(`Failed for token ${idx}:`, {
            code: errorCode,
            message: errorMessage,
            token: fcmTokens[idx]?.substring(0, 20) + '...'
          });
          
          // Log SenderId mismatch specifically
          if (errorCode === 'messaging/mismatched-credential') {
            const projectInfo = getFirebaseProjectInfo();
            console.error(`   🚨 SenderId mismatch detected for this token`);
            console.error(`   Backend Project: ${projectInfo.projectId}`);
          }
        }
      });
    }
    
    return { 
      success: response.successCount > 0, // true if at least one succeeded
      response,
      successCount: response.successCount,
      failureCount: response.failureCount
    };
  } catch (error) {
    console.error('❌ Error sending notifications:', error);
    
    // Handle SenderId mismatch at batch level
    if (error.code === 'messaging/mismatched-credential') {
      const projectInfo = getFirebaseProjectInfo();
      console.error('🚨 SENDER ID MISMATCH DETECTED for batch send!');
      console.error('Backend Project:', projectInfo.projectId);
      console.error('All tokens in this batch are from a different Firebase project');
    }
    
    return { 
      success: false, 
      error: error.message,
      code: error.code
    };
  }
};

// Send notification to topic
const sendNotificationToTopic = async (topic, title, body, data = {}) => {
  try {
    // ✅ FIXED: Sanitize data to ensure all values are strings
    const sanitizedData = sanitizeData({
      ...data,
      click_action: 'FLUTTER_NOTIFICATION_CLICK'
    });

    const message = {
      notification: {
        title,
        body
      },
      data: sanitizedData,
      topic,
      android: {
        priority: 'high',
        notification: {
          sound: 'default',
          channelId: 'order_updates',
          clickAction: 'FLUTTER_NOTIFICATION_CLICK'
        }
      },
      apns: {
        payload: {
          aps: {
            sound: 'default',
            badge: 1,
            category: 'FLUTTER_NOTIFICATION_CLICK'
          }
        }
      },
      webpush: {
        notification: {
          icon: '/icon.png',
          badge: '/badge.png',
          requireInteraction: false
        },
        fcmOptions: {
          link: '/'
        }
      }
    };

    const response = await admin.messaging().send(message);
    console.log('✅ Successfully sent notification to topic:', response);
    return { success: true, response };
  } catch (error) {
    console.error('❌ Error sending notification to topic:', error);
    return { success: false, error: error.message };
  }
};

// Subscribe user to topic
const subscribeToTopic = async (fcmTokens, topic) => {
  try {
    const tokens = Array.isArray(fcmTokens) ? fcmTokens : [fcmTokens];
    const response = await admin.messaging().subscribeToTopic(tokens, topic);
    console.log('✅ Successfully subscribed to topic:', response);
    return { success: true, response };
  } catch (error) {
    console.error('❌ Error subscribing to topic:', error);
    return { success: false, error: error.message };
  }
};

// Unsubscribe user from topic
const unsubscribeFromTopic = async (fcmTokens, topic) => {
  try {
    const tokens = Array.isArray(fcmTokens) ? fcmTokens : [fcmTokens];
    const response = await admin.messaging().unsubscribeFromTopic(tokens, topic);
    console.log('✅ Successfully unsubscribed from topic:', response);
    return { success: true, response };
  } catch (error) {
    console.error('❌ Error unsubscribing from topic:', error);
    return { success: false, error: error.message };
  }
};

module.exports = {
  sendNotificationToDevice,
  sendNotificationToMultipleDevices,
  sendNotificationToTopic,
  subscribeToTopic,
  unsubscribeFromTopic
};